name: Setup
description: Setup Node and install dependencies
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
