@startuml Fetching inventory

actor User as user

participant "bot-manager" as bot_manager
participant "bot" as bot
participant "Message broker" as message_broker

user -> bot_manager: Fetch inventory
activate user

activate bot_manager

bot_manager -> bot_manager: Check cache

alt Inventory is cached
  bot_manager -> user: Return cached inventory
else Inventory is not cached
  bot_manager -> bot_manager: Queue load

  group Load inventory
    bot_manager -> bot: Load inventory
    activate bot
    activate bot_manager
    bot --> bot_manager: Inventory
    deactivate bot
    bot_manager -> bot_manager: Cache inventory
    bot_manager -> message_broker: Publish inventory
    activate message_broker
    message_broker --> bot_manager: Acknowledge
    deactivate message_broker
    end
    bot_manager -> bot_manager: Inventory loaded
  deactivate bot_manager
end

bot_manager --> user: Return inventory
deactivate bot_manager
deactivate user

@enduml
