version: "3.8"
volumes:
  redis:
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass test --appendonly yes --maxmemory-policy noeviction
    expose:
      - "6379"
    volumes:
      - redis:/data
  bptf-manager:
    image: ghcr.io/tf2-automatic/bptf-manager:latest
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "test"
